apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    description: Stores clones of repositories to perform Git operations.
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: gitserver
  name: gitserver
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitserver
  serviceName: gitserver
  template:
    metadata:
      labels:
        app: gitserver
        group: backend
        type: gitserver
        deploy: sourcegraph
    spec:
      containers:
      - name: gitserver
        args: ["run"]
        image: index.docker.io/sourcegraph/gitserver:3.27.5@sha256:33a964bbae136ff14bf5f83b99d8f062a2dbab12a15fcf4f3a44f05a87787ae2
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: rpc
          timeoutSeconds: 5
        ports:
        - containerPort: 3178
          name: rpc
        resources:
          limits:
            cpu: "4"
            memory: 8G
          requests:
            cpu: "4"
            memory: 8G
        volumeMounts:
        - mountPath: /data/repos
          name: repos
        # See the customization guide (../../../docs/configure.md) for information
        # about configuring gitserver to use an SSH key
        # - mountPath: /root/.ssh
        #   name: ssh
      - name: jaeger-agent
        image: index.docker.io/sourcegraph/jaeger-agent:3.27.5@sha256:72158c9fbdb94338ae475edcd595939e6776dfeb2180d660d8d62ad659d95bb1
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        resources:
          limits:
            cpu: "1"
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M
        args:
          - --reporter.grpc.host-port=jaeger-collector:14250
          - --reporter.type=grpc
      securityContext:
        runAsUser: 0
      volumes:
      - name: repos
      # See the customization guide (../../../docs/configure.md) for information
      # about configuring gitserver to use an SSH key
      # - name: ssh
      #   secret:
      #     defaultMode: 384
      #     secretName: gitserver-ssh
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: repos
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          # The size of disk used to mirror your git repositories.
          # If you change this, also change indexed-search's disk size.
          storage: 200Gi
      storageClassName: sourcegraph
